### ISSUE TITLE
Calling startActivity() from outside of an Activity

### ISSUE THREAD

**Issue by Bhat015** [Ali1Ammar/optimization_battery#1]
Unable to open the battery settings. it throws this error

`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?, null, android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`

**Comment by Ali1Ammar** [comment]
hii 
could you test if this this branch [acitivityaware](https://github.com/Ali1Ammar/optimization_battery/tree/acitivityaware) solve the bugs

**Comment by Bhat015** [comment]
Hi,
tested with the branch and it works fine without any issues. 
Thanks for resolving this.
